export const Tags = [
  "Agriculture",
  "Apparel and fashion",
  "Automobile accessories",
  "Baby care",
  "Beauty and personal care",
  "Chemicals",
  "Construction and real estate",
  "Electronic component",
  "Electronics",
  "Energy",
  "Food and beverage",
  "Footwear and accessories",
  "Furniture",
  "Gifts and crafts",
  "Health and medical",
  "Home and garden",
  "Industrial machinery",
  "IT components",
  "Jewelry",
  "Lights and lighting",
  "Luggage bags and cases",
  "Musical instruments",
  "Office and school supplies",
  "Packaging and printing",
  "Pet and pet supplies",
  "Rubber and plastics",
  "Security and protection",
  "Sports and entertainment",
  "Textile and leather product",
  "Toys and games",
  "Transport and shipping",
  "Watches and eyewear",
];
