export const Tags = [
    "Plumber", 
    "Carpenter", 
    "Electrician",
    "plumber",
    "Electrician",
    "Carpenter",
    "landscape",
    "gardening",
    "design",
    "coffee shop",
    "artisan coffee",
    "barista",
    "technology",
    "software",
    "innovation",
    "interior design",
    "contemporary",
    "residential",
    "commercial",
    "bakery",
    "artisan",
    "local",
    "yoga",
    "wellness",
    "classes",
    "design",
    "branding",
    "marketing",
    "bookstore",
    "cafe",
    "coffee",
    "literature",
    "soap",
    "workshop",
    "handmade"
]
